# Generated by Django 4.0.5 on 2022-07-04 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=30, verbose_name='Markaz nomi')),
                ('title_ru', models.CharField(max_length=30, verbose_name='Название центра')),
                ('description_uz', models.TextField(blank=True, default='Tavsif', verbose_name='Markaz tavsifi')),
                ('description_ru', models.TextField(blank=True, default='Описание', verbose_name='Описание центра')),
                ('phone', models.CharField(blank=True, default='None', max_length=20, verbose_name='Telefon raqam')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('image_file', models.ImageField(upload_to='centers/', verbose_name='Markaz rasmi')),
            ],
            options={
                'verbose_name': 'Markaz',
                'verbose_name_plural': 'Markazlar',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=50, verbose_name='Kurs nomi')),
                ('title_ru', models.CharField(max_length=50, verbose_name='Название курса')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description_uz', models.TextField(blank=True, default='Tavsif', verbose_name='Kurs tavsifi')),
                ('description_ru', models.TextField(blank=True, default='Описание', verbose_name='Описание курса')),
                ('price', models.CharField(blank=True, default=0, max_length=20, verbose_name='Narxi')),
                ('duration', models.CharField(blank=True, default='None', max_length=20, verbose_name='Davomiyligi')),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('image_file', models.ImageField(upload_to='courses/', verbose_name='Курс тақырыпының суреті')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главная страница')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=30, verbose_name='Sahifa nomi')),
                ('title_ru', models.CharField(max_length=30, verbose_name='Название страницы')),
                ('description_uz', models.TextField(blank=True, default='Tavsif', verbose_name='Sahifa tavsifi')),
                ('description_ru', models.TextField(blank=True, default='Описание', verbose_name='Описание страницы')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('image_file', models.ImageField(upload_to='pages/', verbose_name='Sahifa rasmi')),
            ],
            options={
                'verbose_name': 'Sahifa',
                'verbose_name_plural': 'Sahifalar',
            },
        ),
        migrations.CreateModel(
            name='ExternalLinks',
            fields=[
                ('title', models.CharField(max_length=30, verbose_name='Havola nomi')),
                ('url', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='URL')),
                ('views', models.IntegerField(default=0, verbose_name='Korinishlar soni')),
                ('pub_day', models.DateField(auto_now_add=True, verbose_name='Yayın tarixi')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.centers')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
            options={
                'verbose_name': 'Havola',
                'verbose_name_plural': 'Havolalar',
                'db_table': 'links',
            },
        ),
    ]
