# Generated by Django 4.0.5 on 2022-06-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('image', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.CharField(max_length=20, verbose_name='Price')),
                ('duration', models.CharField(max_length=20, verbose_name='Duration')),
                ('image', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='')),
            ],
        ),
    ]
