# Generated by Django 4.0.5 on 2022-07-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная страница'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description_uz',
            field=models.TextField(blank=True, default='Tavsif', verbose_name='Kurs tavsifi'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title_uz',
            field=models.CharField(max_length=50, verbose_name='Kurs nomi'),
        ),
    ]
