# Generated by Django 4.0.5 on 2022-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('title_uz', models.CharField(max_length=30, null=True)),
                ('title_ru', models.CharField(max_length=30, null=True)),
                ('description', models.TextField()),
                ('description_uz', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('action', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='title_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
