# Generated by Django 4.0.5 on 2022-07-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centers',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
    ]
