# Generated by Django 4.0.5 on 2022-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_is_main_alter_courses_description_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='description_uz',
            field=models.TextField(blank=True, default='Tavsif', verbose_name='Markaz tavsifi'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='image_file',
            field=models.ImageField(upload_to='centers/', verbose_name='Markaz rasmi'),
        ),
        migrations.AlterField(
            model_name='centers',
            name='title_uz',
            field=models.CharField(max_length=30, verbose_name='Markaz nomi'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='description_uz',
            field=models.TextField(blank=True, default='Tavsif', verbose_name='Sahifa tavsifi'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='image_file',
            field=models.ImageField(upload_to='pages/', verbose_name='Sahifa rasmi'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='title_uz',
            field=models.CharField(max_length=30, verbose_name='Sahifa nomi'),
        ),
    ]
