# Generated by Django 4.0.5 on 2022-06-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_centers_courses_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image_file',
            field=models.ImageField(default='1', upload_to=''),
            preserve_default=False,
        ),
    ]
