# Generated by Django 4.0.5 on 2022-07-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_centers_phone_remove_courses_price'),
        ('courses', '0003_alter_centers_description_uz_and_more'),
    ]

    operations = [
    ]
