# Generated by Django 4.0.5 on 2022-07-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_merge_20220708_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='duration',
        ),
        migrations.AlterField(
            model_name='centers',
            name='image_file',
            field=models.ImageField(upload_to='', verbose_name='Markaz rasmi'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image_file',
            field=models.ImageField(upload_to='', verbose_name='Kurs rasmlari'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='image_file',
            field=models.ImageField(upload_to='', verbose_name='Sahifa rasmi'),
        ),
    ]
