# Generated by Django 4.0.5 on 2022-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('fio', models.CharField(blank=True, max_length=50, null=True, verbose_name='F.I.O.')),
                ('sex', models.CharField(blank=True, max_length=15, null=True, verbose_name='Jinsi')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Yoshi')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefoni raqam')),
                ('center', models.CharField(blank=True, max_length=20, null=True, verbose_name='Markaz')),
                ('course', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kurs')),
                ('registered', models.BooleanField(default=False, verbose_name='Registratsiya qilgan')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
            },
        ),
    ]
