#name: Deploy
#
#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v1
#
#    - name: Copy repository contents via scp
#      uses: appleboy/scp-action@master
#      env:
#        HOST: ${{ secrets.HOST }}
#        USERNAME: ${{ secrets.USERNAME }}
#        PORT: ${{ secrets.PORT }}
#        KEY: ${{ secrets.SSHKEY }}
#      with:
#        source: "."
#        target: "/root/itparkbot"
#
#    - name: Executing remote command
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        USERNAME: ${{ secrets.USERNAME }}
#        PORT: ${{ secrets.PORT }}
#        KEY: ${{ secrets.SSHKEY }}
#        script: |
#          /root/itparkbot/venv/bin/pip install -r /root/itparkbot/req.txt
#          /root/itparkbot/venv/bin/pybabel compile -f -d locales -D mybot
#          systemctl restart itparkbot.service
##          /root/itparkbot/venv/bin/flake8 /root/itparkbot/